"""
World countries data with flag emojis for autocomplete
"""
WORLD_COUNTRIES = [
    {"code": "AF", "name": "Afghanistan", "flag": "🇦🇫"},
    {"code": "AL", "name": "Albania", "flag": "🇦🇱"},
    {"code": "DZ", "name": "Algeria", "flag": "🇩🇿"},
    {"code": "AD", "name": "Andorra", "flag": "🇦🇩"},
    {"code": "AO", "name": "Angola", "flag": "🇦🇴"},
    {"code": "AG", "name": "Antigua and Barbuda", "flag": "🇦🇬"},
    {"code": "AR", "name": "Argentina", "flag": "🇦🇷"},
    {"code": "AM", "name": "Armenia", "flag": "🇦🇲"},
    {"code": "AU", "name": "Australia", "flag": "🇦🇺"},
    {"code": "AT", "name": "Austria", "flag": "🇦🇹"},
    {"code": "AZ", "name": "Azerbaijan", "flag": "🇦🇿"},
    {"code": "BS", "name": "Bahamas", "flag": "🇧🇸"},
    {"code": "BH", "name": "Bahrain", "flag": "🇧🇭"},
    {"code": "BD", "name": "Bangladesh", "flag": "🇧🇩"},
    {"code": "BB", "name": "Barbados", "flag": "🇧🇧"},
    {"code": "BY", "name": "Belarus", "flag": "🇧🇾"},
    {"code": "BE", "name": "Belgium", "flag": "🇧🇪"},
    {"code": "BZ", "name": "Belize", "flag": "🇧🇿"},
    {"code": "BJ", "name": "Benin", "flag": "🇧🇯"},
    {"code": "BT", "name": "Bhutan", "flag": "🇧🇹"},
    {"code": "BO", "name": "Bolivia", "flag": "🇧🇴"},
    {"code": "BA", "name": "Bosnia and Herzegovina", "flag": "🇧🇦"},
    {"code": "BW", "name": "Botswana", "flag": "🇧🇼"},
    {"code": "BR", "name": "Brazil", "flag": "🇧🇷"},
    {"code": "BN", "name": "Brunei", "flag": "🇧🇳"},
    {"code": "BG", "name": "Bulgaria", "flag": "🇧🇬"},
    {"code": "BF", "name": "Burkina Faso", "flag": "🇧🇫"},
    {"code": "BI", "name": "Burundi", "flag": "🇧🇮"},
    {"code": "KH", "name": "Cambodia", "flag": "🇰🇭"},
    {"code": "CM", "name": "Cameroon", "flag": "🇨🇲"},
    {"code": "CA", "name": "Canada", "flag": "🇨🇦"},
    {"code": "CV", "name": "Cape Verde", "flag": "🇨🇻"},
    {"code": "CF", "name": "Central African Republic", "flag": "🇨🇫"},
    {"code": "TD", "name": "Chad", "flag": "🇹🇩"},
    {"code": "CL", "name": "Chile", "flag": "🇨🇱"},
    {"code": "CN", "name": "China", "flag": "🇨🇳"},
    {"code": "CO", "name": "Colombia", "flag": "🇨🇴"},
    {"code": "KM", "name": "Comoros", "flag": "🇰🇲"},
    {"code": "CG", "name": "Congo", "flag": "🇨🇬"},
    {"code": "CR", "name": "Costa Rica", "flag": "🇨🇷"},
    {"code": "HR", "name": "Croatia", "flag": "🇭🇷"},
    {"code": "CU", "name": "Cuba", "flag": "🇨🇺"},
    {"code": "CY", "name": "Cyprus", "flag": "🇨🇾"},
    {"code": "CZ", "name": "Czechia", "flag": "🇨🇿"},
    {"code": "DK", "name": "Denmark", "flag": "🇩🇰"},
    {"code": "DJ", "name": "Djibouti", "flag": "🇩🇯"},
    {"code": "DM", "name": "Dominica", "flag": "🇩🇲"},
    {"code": "DO", "name": "Dominican Republic", "flag": "🇩🇴"},
    {"code": "EC", "name": "Ecuador", "flag": "🇪🇨"},
    {"code": "EG", "name": "Egypt", "flag": "🇪🇬"},
    {"code": "SV", "name": "El Salvador", "flag": "🇸🇻"},
    {"code": "GQ", "name": "Equatorial Guinea", "flag": "🇬🇶"},
    {"code": "ER", "name": "Eritrea", "flag": "🇪🇷"},
    {"code": "EE", "name": "Estonia", "flag": "🇪🇪"},
    {"code": "SZ", "name": "Eswatini", "flag": "🇸🇿"},
    {"code": "ET", "name": "Ethiopia", "flag": "🇪🇹"},
    {"code": "FJ", "name": "Fiji", "flag": "🇫🇯"},
    {"code": "FI", "name": "Finland", "flag": "🇫🇮"},
    {"code": "FR", "name": "France", "flag": "🇫🇷"},
    {"code": "GA", "name": "Gabon", "flag": "🇬🇦"},
    {"code": "GM", "name": "Gambia", "flag": "🇬🇲"},
    {"code": "GE", "name": "Georgia", "flag": "🇬🇪"},
    {"code": "DE", "name": "Germany", "flag": "🇩🇪"},
    {"code": "GH", "name": "Ghana", "flag": "🇬🇭"},
    {"code": "GR", "name": "Greece", "flag": "🇬🇷"},
    {"code": "GD", "name": "Grenada", "flag": "🇬🇩"},
    {"code": "GT", "name": "Guatemala", "flag": "🇬🇹"},
    {"code": "GN", "name": "Guinea", "flag": "🇬🇳"},
    {"code": "GW", "name": "Guinea-Bissau", "flag": "🇬🇼"},
    {"code": "GY", "name": "Guyana", "flag": "🇬🇾"},
    {"code": "HT", "name": "Haiti", "flag": "🇭🇹"},
    {"code": "HN", "name": "Honduras", "flag": "🇭🇳"},
    {"code": "HU", "name": "Hungary", "flag": "🇭🇺"},
    {"code": "IS", "name": "Iceland", "flag": "🇮🇸"},
    {"code": "IN", "name": "India", "flag": "🇮🇳"},
    {"code": "ID", "name": "Indonesia", "flag": "🇮🇩"},
    {"code": "IR", "name": "Iran", "flag": "🇮🇷"},
    {"code": "IQ", "name": "Iraq", "flag": "🇮🇶"},
    {"code": "IE", "name": "Ireland", "flag": "🇮🇪"},
    {"code": "IL", "name": "Israel", "flag": "🇮🇱"},
    {"code": "IT", "name": "Italy", "flag": "🇮🇹"},
    {"code": "JM", "name": "Jamaica", "flag": "🇯🇲"},
    {"code": "JP", "name": "Japan", "flag": "🇯🇵"},
    {"code": "JO", "name": "Jordan", "flag": "🇯🇴"},
    {"code": "KZ", "name": "Kazakhstan", "flag": "🇰🇿"},
    {"code": "KE", "name": "Kenya", "flag": "🇰🇪"},
    {"code": "KI", "name": "Kiribati", "flag": "🇰🇮"},
    {"code": "KP", "name": "North Korea", "flag": "🇰🇵"},
    {"code": "KR", "name": "South Korea", "flag": "🇰🇷"},
    {"code": "KW", "name": "Kuwait", "flag": "🇰🇼"},
    {"code": "KG", "name": "Kyrgyzstan", "flag": "🇰🇬"},
    {"code": "LA", "name": "Laos", "flag": "🇱🇦"},
    {"code": "LV", "name": "Latvia", "flag": "🇱🇻"},
    {"code": "LB", "name": "Lebanon", "flag": "🇱🇧"},
    {"code": "LS", "name": "Lesotho", "flag": "🇱🇸"},
    {"code": "LR", "name": "Liberia", "flag": "🇱🇷"},
    {"code": "LY", "name": "Libya", "flag": "🇱🇾"},
    {"code": "LI", "name": "Liechtenstein", "flag": "🇱🇮"},
    {"code": "LT", "name": "Lithuania", "flag": "🇱🇹"},
    {"code": "LU", "name": "Luxembourg", "flag": "🇱🇺"},
    {"code": "MG", "name": "Madagascar", "flag": "🇲🇬"},
    {"code": "MW", "name": "Malawi", "flag": "🇲🇼"},
    {"code": "MY", "name": "Malaysia", "flag": "🇲🇾"},
    {"code": "MV", "name": "Maldives", "flag": "🇲🇻"},
    {"code": "ML", "name": "Mali", "flag": "🇲🇱"},
    {"code": "MT", "name": "Malta", "flag": "🇲🇹"},
    {"code": "MH", "name": "Marshall Islands", "flag": "🇲🇭"},
    {"code": "MR", "name": "Mauritania", "flag": "🇲🇷"},
    {"code": "MU", "name": "Mauritius", "flag": "🇲🇺"},
    {"code": "MX", "name": "Mexico", "flag": "🇲🇽"},
    {"code": "FM", "name": "Micronesia", "flag": "🇫🇲"},
    {"code": "MD", "name": "Moldova", "flag": "🇲🇩"},
    {"code": "MC", "name": "Monaco", "flag": "🇲🇨"},
    {"code": "MN", "name": "Mongolia", "flag": "🇲🇳"},
    {"code": "ME", "name": "Montenegro", "flag": "🇲🇪"},
    {"code": "MA", "name": "Morocco", "flag": "🇲🇦"},
    {"code": "MZ", "name": "Mozambique", "flag": "🇲🇿"},
    {"code": "MM", "name": "Myanmar", "flag": "🇲🇲"},
    {"code": "NA", "name": "Namibia", "flag": "🇳🇦"},
    {"code": "NR", "name": "Nauru", "flag": "🇳🇷"},
    {"code": "NP", "name": "Nepal", "flag": "🇳🇵"},
    {"code": "NL", "name": "Netherlands", "flag": "🇳🇱"},
    {"code": "NZ", "name": "New Zealand", "flag": "🇳🇿"},
    {"code": "NI", "name": "Nicaragua", "flag": "🇳🇮"},
    {"code": "NE", "name": "Niger", "flag": "🇳🇪"},
    {"code": "NG", "name": "Nigeria", "flag": "🇳🇬"},
    {"code": "NO", "name": "Norway", "flag": "🇳🇴"},
    {"code": "OM", "name": "Oman", "flag": "🇴🇲"},
    {"code": "PK", "name": "Pakistan", "flag": "🇵🇰"},
    {"code": "PW", "name": "Palau", "flag": "🇵🇼"},
    {"code": "PS", "name": "Palestine", "flag": "🇵🇸"},
    {"code": "PA", "name": "Panama", "flag": "🇵🇦"},
    {"code": "PG", "name": "Papua New Guinea", "flag": "🇵🇬"},
    {"code": "PY", "name": "Paraguay", "flag": "🇵🇾"},
    {"code": "PE", "name": "Peru", "flag": "🇵🇪"},
    {"code": "PH", "name": "Philippines", "flag": "🇵🇭"},
    {"code": "PL", "name": "Poland", "flag": "🇵🇱"},
    {"code": "PT", "name": "Portugal", "flag": "🇵🇹"},
    {"code": "QA", "name": "Qatar", "flag": "🇶🇦"},
    {"code": "RO", "name": "Romania", "flag": "🇷🇴"},
    {"code": "RU", "name": "Russia", "flag": "🇷🇺"},
    {"code": "RW", "name": "Rwanda", "flag": "🇷🇼"},
    {"code": "KN", "name": "Saint Kitts and Nevis", "flag": "🇰🇳"},
    {"code": "LC", "name": "Saint Lucia", "flag": "🇱🇨"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines", "flag": "🇻🇨"},
    {"code": "WS", "name": "Samoa", "flag": "🇼🇸"},
    {"code": "SM", "name": "San Marino", "flag": "🇸🇲"},
    {"code": "ST", "name": "São Tomé and Príncipe", "flag": "🇸🇹"},
    {"code": "SA", "name": "Saudi Arabia", "flag": "🇸🇦"},
    {"code": "SN", "name": "Senegal", "flag": "🇸🇳"},
    {"code": "RS", "name": "Serbia", "flag": "🇷🇸"},
    {"code": "SC", "name": "Seychelles", "flag": "🇸🇨"},
    {"code": "SL", "name": "Sierra Leone", "flag": "🇸🇱"},
    {"code": "SG", "name": "Singapore", "flag": "🇸🇬"},
    {"code": "SK", "name": "Slovakia", "flag": "🇸🇰"},
    {"code": "SI", "name": "Slovenia", "flag": "🇸🇮"},
    {"code": "SB", "name": "Solomon Islands", "flag": "🇸🇧"},
    {"code": "SO", "name": "Somalia", "flag": "🇸🇴"},
    {"code": "ZA", "name": "South Africa", "flag": "🇿🇦"},
    {"code": "SS", "name": "South Sudan", "flag": "🇸🇸"},
    {"code": "ES", "name": "Spain", "flag": "🇪🇸"},
    {"code": "LK", "name": "Sri Lanka", "flag": "🇱🇰"},
    {"code": "SD", "name": "Sudan", "flag": "🇸🇩"},
    {"code": "SR", "name": "Suriname", "flag": "🇸🇷"},
    {"code": "SE", "name": "Sweden", "flag": "🇸🇪"},
    {"code": "CH", "name": "Switzerland", "flag": "🇨🇭"},
    {"code": "SY", "name": "Syria", "flag": "🇸🇾"},
    {"code": "TW", "name": "Taiwan", "flag": "🇹🇼"},
    {"code": "TJ", "name": "Tajikistan", "flag": "🇹🇯"},
    {"code": "TZ", "name": "Tanzania", "flag": "🇹🇿"},
    {"code": "TH", "name": "Thailand", "flag": "🇹🇭"},
    {"code": "TL", "name": "Timor-Leste", "flag": "🇹🇱"},
    {"code": "TG", "name": "Togo", "flag": "🇹🇬"},
    {"code": "TO", "name": "Tonga", "flag": "🇹🇴"},
    {"code": "TT", "name": "Trinidad and Tobago", "flag": "🇹🇹"},
    {"code": "TN", "name": "Tunisia", "flag": "🇹🇳"},
    {"code": "TR", "name": "Turkey", "flag": "🇹🇷"},
    {"code": "TM", "name": "Turkmenistan", "flag": "🇹🇲"},
    {"code": "TV", "name": "Tuvalu", "flag": "🇹🇻"},
    {"code": "UG", "name": "Uganda", "flag": "🇺🇬"},
    {"code": "UA", "name": "Ukraine", "flag": "🇺🇦"},
    {"code": "AE", "name": "United Arab Emirates", "flag": "🇦🇪"},
    {"code": "GB", "name": "United Kingdom", "flag": "🇬🇧"},
    {"code": "US", "name": "United States", "flag": "🇺🇸"},
    {"code": "UY", "name": "Uruguay", "flag": "🇺🇾"},
    {"code": "UZ", "name": "Uzbekistan", "flag": "🇺🇿"},
    {"code": "VU", "name": "Vanuatu", "flag": "🇻🇺"},
    {"code": "VE", "name": "Venezuela", "flag": "🇻🇪"},
    {"code": "VN", "name": "Vietnam", "flag": "🇻🇳"},
    {"code": "YE", "name": "Yemen", "flag": "🇾🇪"},
    {"code": "ZM", "name": "Zambia", "flag": "🇿🇲"},
    {"code": "ZW", "name": "Zimbabwe", "flag": "🇿🇼"}
]

WORLD_CITIES = [
    # Major African cities
    {"name": "Abuja", "country_code": "NG"},
    {"name": "Accra", "country_code": "GH"},
    {"name": "Alexandria", "country_code": "EG"},
    {"name": "Algiers", "country_code": "DZ"},
    {"name": "Bamako", "country_code": "ML"},
    {"name": "Brazzaville", "country_code": "CG"},
    {"name": "Cairo", "country_code": "EG"},
    {"name": "Cape Town", "country_code": "ZA"},
    {"name": "Casablanca", "country_code": "MA"},
    {"name": "Dakar", "country_code": "SN"},
    {"name": "Dar es Salaam", "country_code": "TZ"},
    {"name": "Douala", "country_code": "CM"},
    {"name": "Khartoum", "country_code": "SD"},
    {"name": "Kinshasa", "country_code": "CD"},
    {"name": "Lagos", "country_code": "NG"},
    {"name": "Libreville", "country_code": "GA"},
    {"name": "Nairobi", "country_code": "KE"},
    {"name": "Pretoria", "country_code": "ZA"},
    {"name": "Yaoundé", "country_code": "CM"},
    # European cities
    {"name": "Amsterdam", "country_code": "NL"},
    {"name": "Athens", "country_code": "GR"},
    {"name": "Barcelona", "country_code": "ES"},
    {"name": "Berlin", "country_code": "DE"},
    {"name": "Brussels", "country_code": "BE"},
    {"name": "Bucharest", "country_code": "RO"},
    {"name": "Budapest", "country_code": "HU"},
    {"name": "Dublin", "country_code": "IE"},
    {"name": "Helsinki", "country_code": "FI"},
    {"name": "Istanbul", "country_code": "TR"},
    {"name": "Lisbon", "country_code": "PT"},
    {"name": "London", "country_code": "GB"},
    {"name": "Madrid", "country_code": "ES"},
    {"name": "Milan", "country_code": "IT"},
    {"name": "Moscow", "country_code": "RU"},
    {"name": "Munich", "country_code": "DE"},
    {"name": "Paris", "country_code": "FR"},
    {"name": "Prague", "country_code": "CZ"},
    {"name": "Rome", "country_code": "IT"},
    {"name": "Vienna", "country_code": "AT"},
    {"name": "Warsaw", "country_code": "PL"},
    {"name": "Zurich", "country_code": "CH"},
    # Asian cities
    {"name": "Bangkok", "country_code": "TH"},
    {"name": "Beijing", "country_code": "CN"},
    {"name": "Hong Kong", "country_code": "HK"},
    {"name": "Mumbai", "country_code": "IN"},
    {"name": "New Delhi", "country_code": "IN"},
    {"name": "Seoul", "country_code": "KR"},
    {"name": "Shanghai", "country_code": "CN"},
    {"name": "Singapore", "country_code": "SG"},
    {"name": "Tokyo", "country_code": "JP"},
    # Americas cities
    {"name": "Buenos Aires", "country_code": "AR"},
    {"name": "Mexico City", "country_code": "MX"},
    {"name": "New York", "country_code": "US"},
    {"name": "São Paulo", "country_code": "BR"},
    {"name": "Toronto", "country_code": "CA"},
    {"name": "Vancouver", "country_code": "CA"},
]

def get_flag_by_code(code: str) -> str:
    """Récupère le drapeau émoji à partir du code pays"""
    code = code.upper()
    for country in WORLD_COUNTRIES:
        if country['code'] == code:
            return country['flag']
    return '🏳️'  # Drapeau blanc par défaut


def get_all_countries():
    """Retourne tous les pays avec leurs drapeaux"""
    return WORLD_COUNTRIES


def search_countries(query: str):
    """Recherche de pays par nom ou code"""
    query_lower = query.lower()
    results = []
    for country in WORLD_COUNTRIES:
        if query_lower in country['name'].lower() or query_lower in country['code'].lower():
            results.append({
                'code': country['code'],
                'name': country['name'],
                'flag': country['flag']
            })
    return results[:20]  # Limiter à 20 résultats


def search_cities(country_code: str, query: str):
    """Recherche de villes pour un pays donné"""
    query_lower = query.lower()
    results = []
    world_cities_for_country = [c for c in WORLD_CITIES if c['country_code'] == country_code.upper()]
    for city in world_cities_for_country:
        if query_lower in city['name'].lower():
            results.append({
                'name': city['name'],
                'country_code': country_code.upper()
            })
    return results[:20]  # Limiter à 20 résultats
