CREATE TABLE IF NOT EXISTS FONCTION_REFERENCE (
    id_fonction INT AUTO_INCREMENT PRIMARY KEY,
    libelle VARCHAR(200) NOT NULL UNIQUE
);

INSERT IGNORE INTO FONCTION_REFERENCE (libelle)
SELECT DISTINCT TRIM(fonction)
FROM EMPLOYE
WHERE fonction IS NOT NULL
  AND TRIM(fonction) <> '';
