CREATE TABLE IF NOT EXISTS MODULE_STORE_ITEM (
    id_item INT AUTO_INCREMENT PRIMARY KEY,
    module_name VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    created_by INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES EMPLOYE(matricule)
);

CREATE INDEX idx_module_store_name ON MODULE_STORE_ITEM(module_name);
