CREATE TABLE IF NOT EXISTS PUSH_SUBSCRIPTION (
    id_push_subscription INTEGER PRIMARY KEY AUTOINCREMENT,
    matricule INTEGER NOT NULL,
    endpoint VARCHAR(700) NOT NULL UNIQUE,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    user_agent VARCHAR(500),
    active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (matricule) REFERENCES EMPLOYE(matricule)
);

CREATE INDEX IF NOT EXISTS idx_push_subscription_matricule
ON PUSH_SUBSCRIPTION(matricule);
