-- Migration 054 — Matricule alphanumérique (B1 backlog Phase 1)
-- Convertit toutes les colonnes matricule de INT vers VARCHAR(32) pour
-- supporter des matricules tels que "EMP-001", "STG2026-A", etc.
--
-- ATTENTION : faire un BACKUP COMPLET avant exécution. La désactivation
-- temporaire des FK est nécessaire car MySQL refuse l'ALTER TYPE sur PK
-- si des FK pointent encore en INTEGER. On change donc PK puis FK puis
-- on réactive.

SET FOREIGN_KEY_CHECKS = 0;

-- 1) Table EMPLOYE (PK)
ALTER TABLE EMPLOYE
    MODIFY COLUMN matricule VARCHAR(32) NOT NULL,
    MODIFY COLUMN backup_matricule VARCHAR(32) NULL,
    MODIFY COLUMN n1 VARCHAR(32) NULL;

-- 2) Tables FK directes vers EMPLOYE.matricule
ALTER TABLE UTILISATEUR MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE DIRECTION   MODIFY COLUMN id_directeur VARCHAR(32) NULL;
ALTER TABLE DEPARTEMENT MODIFY COLUMN id_responsable VARCHAR(32) NULL;
ALTER TABLE OPERATION   MODIFY COLUMN matricule VARCHAR(32) NOT NULL;

ALTER TABLE CONGE       MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE PERMISSION  MODIFY COLUMN matricule VARCHAR(32) NOT NULL;
ALTER TABLE PERMISSION  MODIFY COLUMN cree_par  VARCHAR(32) NOT NULL;
ALTER TABLE SORTIE      MODIFY COLUMN cree_par  VARCHAR(32) NOT NULL;
ALTER TABLE MISSION     MODIFY COLUMN matricule VARCHAR(32) NOT NULL;
ALTER TABLE FRAIS       MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE FRAIS       MODIFY COLUMN remplacant VARCHAR(32) NULL;
ALTER TABLE FRAIS       MODIFY COLUMN cree_par   VARCHAR(32) NULL;

ALTER TABLE MISSIONNAIRES_MISSION   MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE COMMENTAIRE_MISSION     MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE FRAIS_MISSIONNAIRE      MODIFY COLUMN matricule VARCHAR(32) NOT NULL;
ALTER TABLE VALIDATION              MODIFY COLUMN matricule_validateur VARCHAR(32) NULL;
ALTER TABLE NOTIFICATION            MODIFY COLUMN matricule VARCHAR(32) NULL;
ALTER TABLE REMPLACANT              MODIFY COLUMN matricule_remplacant VARCHAR(32) NOT NULL;
ALTER TABLE ACTIVATION              MODIFY COLUMN matricule VARCHAR(32) NOT NULL;

-- 3) Tables techniques / tasks / posts / push / parcours / evaluations / settings / store
ALTER TABLE TASK              MODIFY COLUMN assigne_a VARCHAR(32) NULL;
ALTER TABLE TASK              MODIFY COLUMN cree_par  VARCHAR(32) NOT NULL;
ALTER TABLE TASK_ASSIGNEE     MODIFY COLUMN matricule_employe VARCHAR(32) NOT NULL;
ALTER TABLE PUSH_SUBSCRIPTION MODIFY COLUMN matricule VARCHAR(32) NOT NULL;
ALTER TABLE TEAM_SPACE_POST   MODIFY COLUMN author_matricule VARCHAR(32) NULL;
ALTER TABLE EVALUATION_FORM         MODIFY COLUMN created_by VARCHAR(32) NULL;
ALTER TABLE EVALUATION_CAMPAGNE     MODIFY COLUMN created_by VARCHAR(32) NULL;
ALTER TABLE EVALUATION              MODIFY COLUMN reviewer_id VARCHAR(32) NOT NULL;
ALTER TABLE EVALUATION              MODIFY COLUMN reviewee_id VARCHAR(32) NOT NULL;
ALTER TABLE FICHE_POSTE             MODIFY COLUMN manager_id VARCHAR(32) NULL;
ALTER TABLE FICHE_POSTE             MODIFY COLUMN employee_id VARCHAR(32) NULL;
ALTER TABLE PARCOURS_EMPLOYE        MODIFY COLUMN matricule VARCHAR(32) NOT NULL;
ALTER TABLE USER_SETTINGS           MODIFY COLUMN user_id VARCHAR(32) NOT NULL;
ALTER TABLE MODULE_STORE_PURCHASE   MODIFY COLUMN created_by VARCHAR(32) NULL;
ALTER TABLE PERSISTENCE_MODULE      MODIFY COLUMN created_by VARCHAR(32) NULL;

SET FOREIGN_KEY_CHECKS = 1;

-- Note : si certaines tables n'existent pas dans votre instance (modules
-- additionnels désactivés), commenter les ALTER correspondants. La
-- migration est idempotente sur les colonnes déjà VARCHAR(32).
